DOMAIN = "adsb_sdr_local"

DEFAULT_PORT = 80
DEFAULT_PATH = "/tar1090/data/aircraft.json"

DEFAULT_SCAN_INTERVAL = 10  # seconds
DEFAULT_MAX_AIRCRAFT = 75

DEFAULT_MIL_PREFIXES = [
  "RRR","QID","RCH","ASY","DUKE","BAF","RAF","CFC","NATO","VIVI","LAGR","NOBLE"
]
